export const ADD_SESSION = 'ADD_SESSION';
export const SEARCH_SESSION = 'SEARCH_SESSION';
export const SEARCH_QUESTION = 'SEARCH_QUESTION';
export const CHANGE_ISDISPLAYANSWER = 'CHANGE_ISDISPLAYANSWER';
export const CHANGE_ISDISPLAYSCROLLTOTOPBUTTON = 'CHANGE_ISDISPLAYSCROLLTOTOPBUTTON';